language: java
sudo: required

jdk:
- oraclejdk8

script:
 - chmod +x ./gradlew build connectedCheck
 ./gradlew clean build -i --continue

before_script: - chmod +x gradlew

after_success:
- ./gradlew cobertura coveralls